import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">LandingPageLostFound</Link>
        </li>
        <li>
          <Link to="/landingpagedeathfuneralannouncements">
            LandingPageDeathFuneralAnnouncements
          </Link>
        </li>
        <li>
          <Link to="/landingpageanniversaries">LandingPageAnniversaries</Link>
        </li>
        <li>
          <Link to="/landingpageservices">LandingPageServices</Link>
        </li>
        <li>
          <Link to="/landingpageaboutus">LandingPageAboutUs</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
